# Generated by Django 5.0.2 on 2024-04-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('business_type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_logo', models.ImageField(blank=True, upload_to='logos/')),
                ('total_products', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'VendorForm',
            },
        ),
    ]
