# Generated by Django 5.0.2 on 2024-04-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorform',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
