# Generated by Django 5.0.2 on 2024-04-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_vendorform_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorform',
            name='Description',
        ),
        migrations.AddField(
            model_name='vendorform',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
