# Generated by Django 5.0.2 on 2024-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_customer_remove_vendorform_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
