# Generated by Django 5.0.2 on 2024-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
