# Generated by Django 5.0.2 on 2024-04-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductForm',
        ),
        migrations.AlterModelTable(
            name='productform',
            table='Product',
        ),
    ]
