# Generated by Django 5.0.2 on 2024-04-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_rename_product_productform_alter_productform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productform',
            table='ProductForm',
        ),
    ]
