# Generated by Django 5.0.2 on 2024-04-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_productform_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productform',
            old_name='name',
            new_name='Productname',
        ),
    ]
