# Generated by Django 5.0.2 on 2024-04-18 10:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_rename_name_productform_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorform',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\odhes\\OneDrive\\Desktop\\dashboard1\\dashboard1\\static/images'), upload_to=''),
        ),
    ]
