<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-15 11:48
=======
# Generated by Django 5.0.3 on 2024-04-02 10:35
>>>>>>> parent of 0a1de22 (forms authentications logic for vendor sign in/login)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organiser', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
