# Generated by Django 5.0.3 on 2024-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendoralt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('vendor_desc', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('vendor_image', models.ImageField(upload_to='vendor_images/')),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
    ]
